module.exports = [
  { id: 1, name: "iPhone 14 Pro Max", category: "Mobiles", originalPrice: 150000, discountedPrice: 120000, discountPercent: 20, imageUrl: "/images/Apple iPhone 14 Pro Max.webp" },
  { id: 2, name: "Nike Air Max", category: "Fashion", originalPrice: 9999, discountedPrice: 7999, discountPercent: 20, imageUrl: "/images/Nike Air Max.webp" },
  { id: 3, name: "HP Victus Gaming", category: "Laptops", originalPrice: 72500, discountedPrice: 58000, discountPercent: 20, imageUrl: "/images/HP Victus Gaming.webp" },
  { id: 4, name: "Sony WH-1000XM5", category: "Headphones", originalPrice: 37490, discountedPrice: 29990, discountPercent: 20, imageUrl: "/images/Sony WH-1000XM5.webp" },
  { id: 5, name: "Apple Watch Series 8", category: "Watches", originalPrice: 56999, discountedPrice: 45999, discountPercent: 20, imageUrl: "/images/Apple Watch Series 8.webp" },
  { id: 6, name: "Lenovo IdeaPad Slim3", category: "Laptops", originalPrice: 59000, discountedPrice: 47000, discountPercent: 20, imageUrl: "/images/Lenovo IdeaPad Slim 3.webp" },
  { id: 7, name: "Samsung S23 Ultra", category: "Mobiles", originalPrice: 125000, discountedPrice: 105000, discountPercent: 16, imageUrl: "/images/Samsung Galaxy S23 Ultra.webp" },
  { id: 8, name: "U.S. Polo T-Shirt", category: "Fashion", originalPrice: 1999, discountedPrice: 1499, discountPercent: 25, imageUrl: "/images/U.S. Polo T-Shirt.webp" },
  { id: 9, name: "Garmin Venu Sq 2", category: "Watches", originalPrice: 31999, discountedPrice: 25999, discountPercent: 19, imageUrl: "/images/Garmin Venu Sq 2.webp" },
  { id: 10, name: "Bose QC 45", category: "Headphones", originalPrice: 29990, discountedPrice: 24990, discountPercent: 17, imageUrl: "/images/Bose-QC-45.webp" },
  { id: 11, name: "Dell Inspiron 15", category: "Laptops", originalPrice: 69000, discountedPrice: 55000, discountPercent: 20, imageUrl: "/images/Dell Inspiron 15.webp" },
  { id: 12, name: "Adidas Hoodie", category: "Fashion", originalPrice: 4499, discountedPrice: 3499, discountPercent: 22, imageUrl: "/images/Adidas Hoodie.webp" },
  { id: 13, name: "OnePlus 11 5G", category: "Mobiles", originalPrice: 67000, discountedPrice: 57000, discountPercent: 15, imageUrl: "/images/OnePlus 11 5G.webp" },
  { id: 14, name: "MSI GF63 Thin", category: "Laptops", originalPrice: 80000, discountedPrice: 64000, discountPercent: 20, imageUrl: "/images/MSI GF63 Thin.webp" },
  { id: 15, name: "Ray-Ban Sunglasses", category: "Fashion", originalPrice: 8999, discountedPrice: 6999, discountPercent: 22, imageUrl: "/images/Ray-Ban Sunglasses.webp" },
  { id: 16, name: "Sennheiser HD 450BT", category: "Headphones", originalPrice: 9990, discountedPrice: 7990, discountPercent: 20, imageUrl: "/images/Sennheiser HD 450BT.webp" },
  { id: 17, name: "HP Pavilion x360", category: "Laptops", originalPrice: 75000, discountedPrice: 60000, discountPercent: 20, imageUrl: "/images/HP Pavilion x360.webp" },
  { id: 18, name: "Boat Rockerz 550", category: "Headphones", originalPrice: 2499, discountedPrice: 1999, discountPercent: 20, imageUrl: "/images/Boat Rockerz 550.webp" },
  { id: 19, name: "Realme GT Neo 5", category: "Mobiles", originalPrice: 42000, discountedPrice: 35000, discountPercent: 17, imageUrl: "/images/Realme GT Neo 5.webp" },
  { id: 20, name: "MacBook Air M1", category: "Laptops", originalPrice: 112500, discountedPrice: 95000, discountPercent: 16, imageUrl: "/images/Apple MacBook Air M1.webp" },
  { id: 21, name: "Fossil Gen 6", category: "Watches", originalPrice: 26999, discountedPrice: 22999, discountPercent: 15, imageUrl: "/images/Fossil Gen 6.webp" },
  { id: 22, name: "Boat Rockerz 255+", category: "Headphones", originalPrice: 1999, discountedPrice: 1599, discountPercent: 20, imageUrl: "/images/Boat Rockerz 255 Pro+.webp" },
  { id: 23, name: "Xiaomi 13 Pro", category: "Mobiles", originalPrice: 86000, discountedPrice: 72000, discountPercent: 16, imageUrl: "/images/Xiaomi 13 Pro.webp" },
  { id: 24, name: "Levi's Denim Jacket", category: "Fashion", originalPrice: 6999, discountedPrice: 5599, discountPercent: 20, imageUrl: "/images/Levi's Denim Jacket.webp" },
  { id: 25, name: "Asus ROG G14", category: "Laptops", originalPrice: 175000, discountedPrice: 140000, discountPercent: 20, imageUrl: "/images/Asus ROG Zephyrus G14.webp" },
  { id: 26, name: "Vivo X90 Pro", category: "Mobiles", originalPrice: 78000, discountedPrice: 65000, discountPercent: 17, imageUrl: "/images/Vivo X90 Pro.webp" },
  { id: 27, name: "Woodland Boots", category: "Fashion", originalPrice: 5999, discountedPrice: 4999, discountPercent: 17, imageUrl: "/images/Woodland Boots.webp" },
  { id: 28, name: "Galaxy Watch 5 Pro", category: "Watches", originalPrice: 42999, discountedPrice: 34999, discountPercent: 19, imageUrl: "/images/Samsung Galaxy Watch 5 Pro.webp" },
  { id: 29, name: "Oppo Reno 10 Pro+", category: "Mobiles", originalPrice: 68000, discountedPrice: 58000, discountPercent: 15, imageUrl: "/images/Oppo Reno 10 Pro+.webp" },
  { id: 30, name: "Skullcandy Crusher", category: "Headphones", originalPrice: 16249, discountedPrice: 12999, discountPercent: 20, imageUrl: "/images/Skullcandy Crusher Evo.webp" },
  { id: 31, name: "Microsoft Surface 5", category: "Laptops", originalPrice: 137500, discountedPrice: 110000, discountPercent: 20, imageUrl: "/images/Microsoft Surface Laptop 5.webp" },
  { id: 32, name: "Nike Air Max", category: "Fashion", originalPrice: 9999, discountedPrice: 7999, discountPercent: 20, imageUrl: "/images/Nike Air Max (2nd variant).webp" },
  { id: 33, name: "JBL Tune 760NC", category: "Headphones", originalPrice: 7499, discountedPrice: 5999, discountPercent: 20, imageUrl: "/images/JBL Tune 760NC.webp" },
  { id: 34, name: "Apple Watch Series 7", category: "Watches", originalPrice: 49999, discountedPrice: 41999, discountPercent: 16, imageUrl: "/images/Apple Watch Series 7.webp" },
  { id: 35, name: "iQOO Neo 7", category: "Mobiles", originalPrice: 34999, discountedPrice: 29999, discountPercent: 14, imageUrl: "/images/iQOO Neo 7.webp" },
  { id: 36, name: "Acer Aspire 7", category: "Laptops", originalPrice: 65000, discountedPrice: 52000, discountPercent: 20, imageUrl: "/images/Acer Aspire 7.webp" },
  { id: 37, name: "U.S. Polo T-Shirt", category: "Fashion", originalPrice: 1999, discountedPrice: 1499, discountPercent: 25, imageUrl: "/images/U.S. Polo T-Shirt1.webp" },
  { id: 38, name: "Google Pixel 7 Pro", category: "Mobiles", originalPrice: 99000, discountedPrice: 85000, discountPercent: 14, imageUrl: "/images/Google Pixel 7 Pro.webp" },
  { id: 39, name: "Fossil Gen 6", category: "Watches", originalPrice: 26999, discountedPrice: 22999, discountPercent: 15, imageUrl: "/images/Fossil Gen 61.webp" },
  { id: 40, name: "Boat Wave Call", category: "Watches", originalPrice: 3599, discountedPrice: 2999, discountPercent: 17, imageUrl: "/images/Boat Wave Call.webp" },
];
